// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAL0mzXqjQvJDfqFdmdld5NYsa2sLDwlg',
    appId: '1:1041036133000:web:c00abc75d2dfe7c3d0953d',
    messagingSenderId: '1041036133000',
    projectId: 'in-bound-app',
    authDomain: 'in-bound-app.firebaseapp.com',
    storageBucket: 'in-bound-app.appspot.com',
    measurementId: 'G-57PML22PND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_LdRfint13QacW1VZE_qdrnpZgOsPLEA',
    appId: '1:1041036133000:android:15392161a0f1c632d0953d',
    messagingSenderId: '1041036133000',
    projectId: 'in-bound-app',
    storageBucket: 'in-bound-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjsWghlwrDWVZhphw2xy1UO4Znjd_gOOE',
    appId: '1:1041036133000:ios:1107f26e223cc2fbd0953d',
    messagingSenderId: '1041036133000',
    projectId: 'in-bound-app',
    storageBucket: 'in-bound-app.appspot.com',
    iosBundleId: 'tech.glactic.inbound',
  );
}
